// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

#ifndef SECRET_DEVICE_KEY
	#define SECRET_DEVICE_KEY	  "YOUR KEY"
	const char THING_ID[]           = "YOUR ID";
	const char DEVICE_LOGIN_NAME[]  = "YOUR LogIN";
#endif

const char DEVICE_KEY[]   = SECRET_DEVICE_KEY;    // Secret device password

void onOnValve1Change();
void onOnValve2Change();
void onOnBothValveChange();
void onMsgChange();

CloudSwitch onValve1;
CloudSwitch onValve2;
CloudSwitch onBothValve;
String msg;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(onValve1, READWRITE, ON_CHANGE, onOnValve1Change);
  ArduinoCloud.addProperty(onValve2, READWRITE, ON_CHANGE, onOnValve2Change);
  ArduinoCloud.addProperty(onBothValve, READWRITE, ON_CHANGE, onOnBothValveChange);
  ArduinoCloud.addProperty(msg, READWRITE, ON_CHANGE, onMsgChange);

}

WiFiConnectionHandler *ArduinoIoTPreferredConnection;
